name: CI
on: [push, pull_request]
jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        jdk: [ 8 ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v5
      - name: Set up JDK ${{ matrix.jdk }}
        uses: actions/setup-java@v5
        with:
          java-version: ${{ matrix.jdk }}
          distribution: liberica
          cache: maven
      - name: Build with Maven
        run: mvn -V -B package -DskipTests
      - name: Run Tests
        run: mvn -V -B verify